# Generated by Django 4.0.1 on 2022-02-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lukeshop', '0003_rename_basketitems_basketitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_addr',
            field=models.TextField(default=''),
        ),
    ]
