# Generated by Django 4.0.1 on 2022-01-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lukeshop', '0002_basket_product_order_basketitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasketItems',
            new_name='BasketItem',
        ),
    ]
